# Generated by Django 4.2.4 on 2023-12-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
