# Generated by Django 4.2 on 2023-09-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("product_sku", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("price", models.FloatField(blank=True, default=0)),
                ("availability", models.IntegerField(blank=True, default=0)),
                ("quantity", models.IntegerField(blank=True, default=0)),
                ("create_date", models.DateTimeField(auto_now=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.categories",
                    ),
                ),
                (
                    "sub_categoery",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.subcategories",
                    ),
                ),
            ],
        ),
    ]
