# Generated by Django 4.2.4 on 2023-09-05 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="images",
            name="product_id",
        ),
        migrations.DeleteModel(
            name="Categories",
        ),
        migrations.DeleteModel(
            name="Images",
        ),
    ]
