# Generated by Django 4.2.4 on 2023-09-05 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Images",
        ),
    ]
