# Generated by Django 4.2.4 on 2023-09-30 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_orders_available_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="available_quantity",
        ),
    ]
