# Generated by Django 4.2.4 on 2023-09-30 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_product_quantity"),
        ("order", "0004_cart_remove_orders_products_delete_orderproduct_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="cart_Items",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.cartitem",
            ),
            preserve_default=False,
        ),
    ]
