# Generated by Django 4.2.4 on 2023-09-30 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_remove_cart_products_remove_cart_quantity_cartitem_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="cart_Items",
            new_name="cart_items",
        ),
    ]
