# Generated by Django 4.2.4 on 2023-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_remove_cart_products_remove_cart_quantity_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="flag_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
