# Generated by Django 4.2.4 on 2023-09-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_rename_cart_items_cart_cart_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="cart_items",
        ),
        migrations.AddField(
            model_name="cart",
            name="cart_items",
            field=models.ManyToManyField(to="order.cartitem"),
        ),
    ]
