# Generated by Django 4.2.4 on 2023-10-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_cartitem_flag_reason_cartitem_is_flagged"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="flag_reason",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="is_flagged",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="is_exclude",
            field=models.BooleanField(
                db_comment="to check the item that need to be exclude from the cart",
                default=False,
            ),
        ),
    ]
